<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vts_evaluation</name>
  <version>1.0.0</version>
  <description>Offline evaluation metrics CLI.</description>
  <maintainer email="manuelrodriguez@alu.comillas.edu">Manuel Rodriguez Villegas</maintainer>
  <license>MIT</license>
  <depend>vts_core</depend>
  <depend>vts_players</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
